# Generated by Django 3.2.16 on 2022-11-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_deal_item_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name': 'Deal', 'verbose_name_plural': 'Deals'},
        ),
        migrations.RemoveField(
            model_name='deal',
            name='date',
        ),
    ]
