# Generated by Django 3.2.16 on 2022-11-05 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_auto_20221105_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Deal date'),
        ),
    ]
