# Generated by Django 3.2.16 on 2022-11-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_deal_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.FloatField(default='0', verbose_name='Profit')),
            ],
            options={
                'verbose_name': 'Profit',
                'verbose_name_plural': 'Profit',
            },
        ),
    ]
