# Generated by Django 3.2.16 on 2022-11-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_alter_deal_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='author',
        ),
    ]
