# Generated by Django 3.2.16 on 2022-11-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0014_auto_20221114_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='profit_on_sale',
            field=models.FloatField(default='0', verbose_name='Profit on sale'),
        ),
    ]
